### ISSUE TITLE
Meaningless error message

### ISSUE THREAD

**Issue by wmeeusse** [ros/pluginlib#2] opened 2012-11-01 01:40 UTC
I'm using plugins in a pure catkin environment, where both the plugins and the code that calls the plugins is in catkin. When instantiating the plugin loader, I get the following (meaningless?) error:

[ERROR] [1351729666.226378607]: Could not find package name for class /home/wim/stacks/groovy/catkin_ws/src/joint_state_controller/joint_state_plugin.xml

What does this mean? The xml file is a class? Does it fail to find a package, or just the name of a package? I'm not sure what to make of this.

It would also be great if the error message could be much more meaningful, so I'd have some idea of what to fix.

**Comment by dirk-thomas** [comment] 2012-11-01 02:04
Duplicate of #1. The message states exactly what happens: the package name of that plugin class could not be determined.

This is not supposed to happen. It appeared because resolving wet and dry stuff is still in a flux - if it would appear again the user has no chance to resolve that since it would be a problem of the underlying tools.

**Comment by wmeeusse** [comment] 2012-11-01 02:27
It's still not clear to me, but at this point my best suggestion for an error message would be:

Could not find element xxx with the package name in the xml file /home/wim/stacks/groovy/catkin_ws/src/joint_state_controller/joint_state_plugin.xml. Please update this xml file.

The message should also give you an idea of what you need to fix. If this is not correct, please help me out in trying to come up with an alternative. I doubt that I'm the only one having trouble understanding the message.

**Comment by dirk-thomas** [comment] 2012-11-01 02:38
The error message is not due to a bug in the xml.

As stated above ROS is not able to find the corresponding package name to which this xml file belongs. This was due to different behavior of rospack and pluginlib in deciding how to identify packages. This issue has been resolved.

Anyway the error message can not give the user an idea what he needs to do because he has no way of fixing the problem.

**Closed as completed by dirk-thomas** 2012-11-01 02:38 UTC

**Comment by wmeeusse** [comment] 2012-11-01 02:55
To provide an answer to the ticket, based on the comment in #1:

Pluginlib can't find the file "manifest.xml" or "package.xml" at the same directory level as the plugin XML file, so it can't be sure that this directory is actually a package.
